version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cyber-analyzer-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./cyber.db
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
    networks:
      - cyber_net

  frontend:
    build: ./frontend
    container_name: cyber-analyzer-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - cyber_net

networks:
  cyber_net:
    driver: bridge
